name: cicd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Run performance tests
        run: python test/performance_test.py

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run check models script
        run: python .github/workflows/check_models.py

      - name: Read deploy list
        id: deploylist
        run: |
          if [ -f deploy_list.txt ]; then
            cat deploy_list.txt
            echo "DEPLOY_MODELS=$(cat deploy_list.txt | xargs)" >> $GITHUB_ENV
          else
            echo "No deploy list found."
            echo "DEPLOY_MODELS=" >> $GITHUB_ENV
          fi

      - name: Deploy models to VM
        if: env.DEPLOY_MODELS != ''
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: ${{ env.DEPLOY_MODELS }}
          target: "/home/app/models/"
